# Generated by Django 4.1.2 on 2022-11-19 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('subject', models.CharField(max_length=300, null=True)),
                ('body', models.TextField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('record', models.FileField(blank=True, null=True, upload_to='records/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='post_dislikes', to='users.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to='users.profile')),
                ('tags', models.ManyToManyField(to='posts.tag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to='users.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to='users.profile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
