# Generated by Django 4.1 on 2022-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="record",
            field=models.FileField(blank=True, null=True, upload_to="records/"),
        ),
    ]
