# Generated by Django 4.1 on 2022-09-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_remove_message_conversation_remove_message_sender_and_more"),
        ("posts", "0005_rate_rater"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="comment_dislikes", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="comment_likes", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="post_dislikes", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="post_likes", to="users.profile"
            ),
        ),
        migrations.DeleteModel(name="Rate",),
    ]
