# Generated by Django 4.1 on 2022-08-14 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_instrument_level_alter_instrument_player"),
    ]

    operations = [
        migrations.RemoveField(model_name="instrument", name="player",),
        migrations.AddField(
            model_name="instrument",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
    ]
