# Generated by Django 4.1 on 2022-08-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_instrument_player_instrument_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="level",
            field=models.DecimalField(
                choices=[
                    (1, "novice"),
                    (2, "beginner"),
                    (3, "intermediate"),
                    (4, "advanced"),
                    (5, "expert"),
                ],
                decimal_places=0,
                default=1,
                max_digits=1,
            ),
        ),
    ]
