# Generated by Django 4.1 on 2022-08-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="name", new_name="first_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
