# Generated by Django 4.1 on 2022-08-17 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0006_rename_name_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friend",
            field=models.ManyToManyField(
                related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
