# Generated by Django 4.1 on 2022-08-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_profile_friend"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="friend",),
    ]
