# Generated by Django 4.1 on 2022-08-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_profile_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friend",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
