# Generated by Django 4.1 on 2022-08-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_friend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="level",
            field=models.CharField(
                choices=[
                    ("Novice", "Novice"),
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Expert", "Expert"),
                ],
                max_length=20,
            ),
        ),
    ]
