# Generated by Django 4.1 on 2022-08-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_instrument_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="message", name="body", field=models.TextField(null=True),
        ),
    ]
