# Generated by Django 4.1 on 2022-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_profile_followers_remove_profile_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
