# Generated by Django 4.1 on 2022-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_follow_created_alter_follow_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to="users.profile"
            ),
        ),
    ]
