# Generated by Django 4.1 on 2022-08-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_follow_follower"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="email",),
    ]
