# Generated by Django 4.1 on 2022-08-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_remove_message_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(model_name="message", name="subject",),
    ]
