# Generated by Django 4.1 on 2022-08-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_conversation_message_conversation"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="participants",),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
