# Generated by Django 4.1 on 2022-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_conversation_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="name",),
    ]
