# Generated by Django 4.1 on 2022-08-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_remove_message_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["created"]},
        ),
    ]
