# Generated by Django 4.1.2 on 2022-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_profile_bio'),
        ('notification', '0002_alter_notification_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='to_users',
            field=models.ManyToManyField(related_name='to_user', to='users.profile'),
        ),
    ]
