# Generated by Django 4.1.2 on 2022-10-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_to_user_notification_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
