# Generated by Django 4.1.2 on 2022-10-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
    ]
