# Generated by Django 4.1.2 on 2022-11-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
    ]
