# Generated by Django 4.1.2 on 2022-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
