# Generated by Django 4.1.2 on 2022-10-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_jamrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JamRequest',
        ),
    ]
