# Generated by Django 4.1.2 on 2022-11-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_profile_bio'),
        ('chat', '0009_delete_jamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='not_show_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_show', to='users.profile'),
        ),
    ]
