# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_profile_bio'),
        ('chat', '0010_message_not_show_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='not_show_for',
            field=models.ManyToManyField(blank=True, related_name='not_show_conversation', to='users.profile'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='not_show_for',
        ),
        migrations.AddField(
            model_name='message',
            name='not_show_for',
            field=models.ManyToManyField(blank=True, related_name='not_show_message', to='users.profile'),
        ),
    ]
